apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy3
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      type: webserver2
      env: dev
  template:
    metadata:
      name: mynginx
      labels:
        type: webserver2
        env: dev
    spec: 
      serviceAccountName: v1
      containers:
      - name: mynginx3
        image: nginx
